version: '3.8'

services:
  web:
    build: .
    ports:
      - "7755:7755"
    environment:
      - FLASK_APP=core/server.py
      - FLASK_ENV=development
      - GUNICORN_PORT=7755
      - GUNICORN_WORKERS=2
      - GUNICORN_LOG_LEVEL=debug
    volumes:
      - .:/app
      - sqlite_data:/app/core
    command: >
      sh -c "flask db upgrade -d core/migrations/ &&
             /app/run.sh"

volumes:
  sqlite_data:
